name: ok_http2
version: 1.0.0
description: A package:http BaseClient that speaks HTTP/2, and can maintain connections.
homepage: https://github.com/amondnet/ok/package/http2_client
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  http: ^0.12.0
  http2: ^1.0.0
  http_parser: ^3.0.0
  tuple: ^1.0.0
dev_dependencies:
  angel_framework: ^2.0.0
  cli_repl: ^0.2.0
  pedantic: ^1.0.0
  test: ^1.0.0