name: retrofit_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/amondnet/ok

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
