name: ok_http2

on: [push, pull_request]

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ["http2"]
        version: ["latest", "dev"]

    container:
      image: google/dart:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: package/${{ matrix.package }}
        run: |
          pub get
          pub global activate test_coverage
          pub global activate remove_from_coverage

      #- name: Analyze
      #  working-directory: package/${{ matrix.package }}
      #  run: dartanalyzer --fatal-infos --fatal-warnings .

      - name: Run tests
        working-directory: package/${{ matrix.package }}
        run: |
          pub run test
          pub global run test_coverage --badge false

      - name: push
        uses: github-actions-x/commit@v2.6
        if: ${{ matrix.version == 'latest' && github.event_name == 'push' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish'
          #force-add: 'true'
          files: coverage_badge.svg
          name: GitHub Action
          email: action@github.com
          rebase: 'true' # pull abd rebase before commit

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        if: ${{ matrix.version == 'latest' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./package/${{ matrix.package }}/coverage/lcov.info